#!/usr/bin/env bash
set -euo pipefail

# Maps environment-prefixed secrets/variables to EXPO_PUBLIC_* env vars.
# Usage: map_runtime_env.sh <ENV_PREFIX>
#
# Expects these env vars set by the workflow step's env: block:
#   TURN_ON_FIREBASE, RETRIES_VALUE, RETRY_DELAY_VALUE,
#   PROD_PUBLIC_SUPABASE_URL, DEV_PUBLIC_SUPABASE_URL,
#   PROD_PUBLIC_SUPABASE_ANON_KEY, DEV_PUBLIC_SUPABASE_ANON_KEY,
#   PROD_SUPABASE_ACCESS_TOKEN, DEV_SUPABASE_ACCESS_TOKEN

ENV_PREFIX="${1:?Usage: map_runtime_env.sh <ENV_PREFIX>}"

echo "EXPO_PUBLIC_TURN_ON_FIREBASE=$TURN_ON_FIREBASE" >> "$GITHUB_ENV"
echo "RETRIES=$RETRIES_VALUE" >> "$GITHUB_ENV"
echo "RETRY_DELAY=$RETRY_DELAY_VALUE" >> "$GITHUB_ENV"

if [ "$ENV_PREFIX" = "PROD" ]; then
  echo "EXPO_PUBLIC_SUPABASE_URL=$PROD_PUBLIC_SUPABASE_URL" >> "$GITHUB_ENV"
  echo "EXPO_PUBLIC_SUPABASE_ANON_KEY=$PROD_PUBLIC_SUPABASE_ANON_KEY" >> "$GITHUB_ENV"
  echo "SUPABASE_ACCESS_TOKEN=$PROD_SUPABASE_ACCESS_TOKEN" >> "$GITHUB_ENV"
else
  echo "EXPO_PUBLIC_SUPABASE_URL=$DEV_PUBLIC_SUPABASE_URL" >> "$GITHUB_ENV"
  echo "EXPO_PUBLIC_SUPABASE_ANON_KEY=$DEV_PUBLIC_SUPABASE_ANON_KEY" >> "$GITHUB_ENV"
  echo "SUPABASE_ACCESS_TOKEN=$DEV_SUPABASE_ACCESS_TOKEN" >> "$GITHUB_ENV"
fi
