#!/usr/bin/env bash
set -euo pipefail

# Maps environment-prefixed secrets/variables to EXPO_PUBLIC_* env vars.
# Usage: map_runtime_env.sh <ENV_PREFIX>
#
# Expects these env vars set by the workflow step's env: block:
#   TURN_ON_FIREBASE, RETRIES_VALUE, RETRY_DELAY_VALUE,
#   PROD_PUBLIC_SUPABASE_URL, DEV_PUBLIC_SUPABASE_URL,
#   PROD_PUBLIC_SUPABASE_ANON_KEY, DEV_PUBLIC_SUPABASE_ANON_KEY,
#   PROD_SUPABASE_ACCESS_TOKEN, DEV_SUPABASE_ACCESS_TOKEN,
#   FIREBASE_API_KEY, FIREBASE_APP_ID, FIREBASE_AUTH_DOMAIN,
#   FIREBASE_MEASUREMENT_ID, FIREBASE_MESSAGING_SENDER_ID,
#   FIREBASE_PROJECT_ID, FIREBASE_STORAGE_BUCKET, FIREBASE_VAPID_KEY

ENV_PREFIX="${1:?Usage: map_runtime_env.sh <ENV_PREFIX>}"

echo "EXPO_PUBLIC_TURN_ON_FIREBASE=$TURN_ON_FIREBASE" >> "$GITHUB_ENV"
echo "RETRIES=$RETRIES_VALUE" >> "$GITHUB_ENV"
echo "RETRY_DELAY=$RETRY_DELAY_VALUE" >> "$GITHUB_ENV"

echo "EXPO_PUBLIC_FIREBASE_API_KEY=${FIREBASE_API_KEY:-}" >> "$GITHUB_ENV"
echo "EXPO_PUBLIC_FIREBASE_APP_ID=${FIREBASE_APP_ID:-}" >> "$GITHUB_ENV"
echo "EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN:-}" >> "$GITHUB_ENV"
echo "EXPO_PUBLIC_FIREBASE_MEASUREMENT_ID=${FIREBASE_MEASUREMENT_ID:-}" >> "$GITHUB_ENV"
echo "EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID:-}" >> "$GITHUB_ENV"
echo "EXPO_PUBLIC_FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID:-}" >> "$GITHUB_ENV"
echo "EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET:-}" >> "$GITHUB_ENV"
echo "EXPO_PUBLIC_FIREBASE_VAPID_KEY=${FIREBASE_VAPID_KEY:-}" >> "$GITHUB_ENV"

if [ "$ENV_PREFIX" = "PROD" ]; then
  echo "EXPO_PUBLIC_SUPABASE_URL=$PROD_PUBLIC_SUPABASE_URL" >> "$GITHUB_ENV"
  echo "EXPO_PUBLIC_SUPABASE_ANON_KEY=$PROD_PUBLIC_SUPABASE_ANON_KEY" >> "$GITHUB_ENV"
  echo "SUPABASE_ACCESS_TOKEN=$PROD_SUPABASE_ACCESS_TOKEN" >> "$GITHUB_ENV"
else
  echo "EXPO_PUBLIC_SUPABASE_URL=$DEV_PUBLIC_SUPABASE_URL" >> "$GITHUB_ENV"
  echo "EXPO_PUBLIC_SUPABASE_ANON_KEY=$DEV_PUBLIC_SUPABASE_ANON_KEY" >> "$GITHUB_ENV"
  echo "SUPABASE_ACCESS_TOKEN=$DEV_SUPABASE_ACCESS_TOKEN" >> "$GITHUB_ENV"
fi
