name: Android CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - '**/*.mdx'
      - 'docs/**'
      - 'scripts/**'
      - '.editorconfig'
      - '.gitattributes'
      - '.gitignore'
      - '.nvmrc'
      - '.node-version'
      - '.prettierignore'
      - '.prettierrc'
      - '.prettierrc.*'
      - '.eslintrc'
      - '.eslintrc.*'
      - 'CODEOWNERS'
      - 'LICENSE*'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.mdx'
      - 'docs/**'
      - 'scripts/**'
      - '.editorconfig'
      - '.gitattributes'
      - '.gitignore'
      - '.nvmrc'
      - '.node-version'
      - '.prettierignore'
      - '.prettierrc'
      - '.prettierrc.*'
      - '.eslintrc'
      - '.eslintrc.*'
      - 'CODEOWNERS'
      - 'LICENSE*'
  workflow_dispatch:

permissions:
  contents: read

env:
  ANDROID_TARGET: 'google_apis'
  ANDROID_API_LEVEL: 35
  MAESTRO_VERSION: '2.0.6'
  FASTLANE_VERSION: '2.228.0'
  RETRIES: ${{ vars.RETRIES }}
  RETRY_DELAY: ${{ vars.RETRY_DELAY }}

concurrency:
  group: android-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:

  android-hosted:
    name: Build • E2E (Android) - Hosted Ubuntu
    if: vars.USE_SELF_HOSTED != 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      ANDROID_SDK_DIR: $HOME/Library/Android/sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 24
        uses: actions/setup-node@v4
        with:
          node-version: 24.1.0
          cache: 'npm'

      - name: Setup Ruby (for Fastlane)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler: 'none'

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install deps
        run: npm ci

      - name: Install EAS CLI
        shell: bash
        run: |
          npm i -g eas-cli@16.23.0
          eas --version

      - name: Make CI scripts executable
        run: chmod +x .github/scripts/*.sh

      - name: Setup Fastlane
        shell: bash
        run: .github/scripts/setup_fastlane.sh  "${{ env.FASTLANE_VERSION }}"

      - name: Doctor
        run: npm run doctor
        continue-on-error: true

      - name: Verify Expo/RN dependency alignment
        shell: bash
        run: |
          set -e
          npx expo --version || true
          node -e "console.log('react-native', require('react-native/package.json').version)" || true
          node -e "console.log('expo', require('expo/package.json').version)" || true
          # Strict: fail if mismatched so lockfile must be updated in a PR
          if ! npx expo install --check; then
            echo "❌ Expo dependency mismatch. Run 'npx expo install --fix' locally and commit the updated package-lock.json."
            exit 1
          fi

      - name: Setup Maestro
        shell: bash
        run: .github/scripts/setup_maestro.sh "${{ env.MAESTRO_VERSION }}"

      # Lean caching: only Gradle + Maestro to stay under 10GB org-wide cache budget
      - name: Cache Gradle (caches + wrapper + project .gradle)
        id: gradle-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            android/.gradle
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'android/**/build.gradle', 'android/**/gradle.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Create debug keystore
        run: |
          mkdir -p android
          keytool -genkeypair -v \
            -keystore "android/debug.keystore" \
            -storepass android -keypass android \
            -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=Android Debug,O=Android,C=US"

      - name: Write signing props for Gradle
        run: |
          echo "android.injected.signing.store.file=$PWD/android/debug.keystore" >> android/gradle.properties
          echo "android.injected.signing.store.password=android"               >> android/gradle.properties
          echo "android.injected.signing.key.alias=androiddebugkey"            >> android/gradle.properties
          echo "android.injected.signing.key.password=android"                 >> android/gradle.properties

      - name: Compute Android build fingerprint
        id: android_fingerprint
        shell: bash
        run: |
          set -euo pipefail

          FILES="$(git ls-files \
            'android/**' \
            'app.json' \
            'app.config.*' \
            'eas.json' \
            'package.json' \
            'package-lock.json' \
            'gradlew' \
            '**/*.gradle*' \
            'gradle.properties' \
            'babel.config.*' \
            'metro.config.*' \
            'tamagui.config.ts' \
            'tsconfig.json' \
            'index.*' \
            'src/**' \
            'assets/**' \
            '**/*.png' '**/*.svg' '**/*.ttf' '**/*.otf' \
            '.env*' \
            'patches/**' \
          )"

          # Add environment “salt” so changes in toolchain also invalidate cache
          SALT="node=$(node -v);java=$(java -version 2>&1 | head -n1)"

          if [ -z "$FILES" ]; then
            # No matching files (unlikely) – still produce a stable, non-empty key
            HASH=$( (echo "$SALT"; echo "<no-files>") | shasum -a 256 | awk '{print $1}' )
          else
            # Hash SALT + file list + per-file contents
            HASH=$( (echo "$SALT"; echo "$FILES"; echo "$FILES" | xargs -I{} shasum "{}") \
              | shasum -a 256 | awk '{print $1}' )
          fi

          echo "hash=$HASH" >> "$GITHUB_OUTPUT"
          echo "🔑 ANDROID_FINGERPRINT=$HASH"

      - name: Restore cached APK
        id: apk-cache
        uses: actions/cache/restore@v4
        with:
          path: ./*.apk
          key: android-apk-${{ steps.android_fingerprint.outputs.hash }}

      - name: Build e2erelease APK
        if: steps.apk-cache.outputs.cache-hit != 'true'
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          set -e
          ATTEMPTS="${RETRIES:-2}"
          DELAY="${RETRY_DELAY:-5}"

          for attempt in $(seq 1 "$ATTEMPTS"); do
            echo "🏗️ Build attempt $attempt/$ATTEMPTS"
            if eas build --platform android --profile e2eRelease --local --non-interactive; then
              echo "✅ Build succeeded"
              exit 0
            fi
            if [ "$attempt" -lt "$ATTEMPTS" ]; then
              echo "⚠️ Build failed; retrying in $DELAY s..."
              sleep "$DELAY"
            fi
          done

          echo "❌ Build failed after $ATTEMPTS attempts"
          exit 1

      - name: Locate APK artifact & app.json
        id: find_apk
        shell: bash
        run: |
          set -euo pipefail
          APK="$(ls -1t ./*.apk 2>/dev/null | head -n1 || true)"
          echo "APK=$APK"
          echo "apk=$APK" >> $GITHUB_OUTPUT
          [ -n "$APK" ] || (echo "No APK found in repo root."; ls -alh .; exit 1)

          PKG=$(node -p "require('./app.json').expo.android.package")
          echo "PKG=$PKG"
          echo "pkg=$PKG" >> $GITHUB_OUTPUT
          [ -n "$PKG" ] || (echo "No PKG found in repo root."; ls -alh .; exit 1)

      - name: Save APK to cache
        if: steps.apk-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: ${{ steps.find_apk.outputs.apk }}
          key: android-apk-${{ steps.android_fingerprint.outputs.hash }}

      - name: Upload Gradle reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-reports-android-hosted
          path: |
            android/build/reports/**
            android/app/build/reports/**
          if-no-files-found: ignore

      - name: Save Gradle cache (post-build)
        if: always() && steps.gradle-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            android/.gradle
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'android/**/build.gradle', 'android/**/gradle.properties') }}

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run E2E tests
        id: e2e_android
        uses: reactivecircus/android-emulator-runner@v2
        timeout-minutes: 30 # Android emulators are slow
        with:
          api-level: ${{ env.ANDROID_API_LEVEL }}
          target: ${{ env.ANDROID_TARGET }}
          arch: x86_64
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          disable-animations: true
          script: .github/scripts/android_run_e2e.sh ${{ steps.find_apk.outputs.apk }} ${{ steps.find_apk.outputs.pkg }}

      - name: Collect emulator logs on failure
        if: failure() && steps.e2e_android.outcome == 'failure'
        shell: bash
        run: |
          echo "Collecting emulator diagnostics..."
          adb logcat -d > e2e-artifacts/emulator.log || true
          adb shell "getprop" > e2e-artifacts/device-props.txt || true
          mkdir -p e2e-artifacts
          echo "✅ Logs collected"

      - name: Upload E2E artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-artifacts-android-hosted
          path: |
            e2e-artifacts/**/*
            android/app/build/reports/**
          include-hidden-files: true

  android-selfhosted:
    name: Lint • Test • Build • E2E (Android) - Self-hosted MacOS
    if: vars.USE_SELF_HOSTED == 'true'
    runs-on: [self-hosted, macos, arm64]
    timeout-minutes: 45
    concurrency:
      group: selfhosted-mobile-${{ github.repository }}
      cancel-in-progress: false
    env:
      ANDROID_SDK_DIR: $HOME/Library/Android/sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Node 24
        uses: actions/setup-node@v4
        with:
          node-version: 24.1.0
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Check EAS CLI
        shell: bash
        run: |
          if ! command -v eas >/dev/null 2>&1; then
            echo "❌ EAS CLI not found on this runner."
            echo "Install it globally: npm i -g eas-cli@16.23.0"
            exit 1
          fi
          eas --version

      - name: Verify Expo/RN dependency alignment
        shell: bash
        run: |
          set -e
          npx expo --version || true
          node -e "console.log('react-native', require('react-native/package.json').version)" || true
          node -e "console.log('expo', require('expo/package.json').version)" || true
          # Strict: fail if mismatched so lockfile must be updated in a PR
          if ! npx expo install --check; then
            echo "❌ Expo dependency mismatch. Run 'npx expo install --fix' locally and commit the updated package-lock.json."
            exit 1
          fi

      - name: Make CI scripts executable
        run: chmod +x .github/scripts/*.sh

      - name: Setup Fastlane
        shell: bash
        run: .github/scripts/setup_fastlane.sh  "${{ env.FASTLANE_VERSION }}"

      - name: Setup Maestro
        shell: bash
        run: .github/scripts/setup_maestro.sh "${{ env.MAESTRO_VERSION }}"

      - name: Check formatting
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Unit tests
        run: npm run test -- --coverage

      # - name: Install GPG
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y gnupg

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v5
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: ./coverage/lcov.info
      #     slug: org/repo
      #     flags: selfhosted-android
      #     fail_ci_if_error: false

      - name: Doctor
        run: npm run doctor
        continue-on-error: true

      # Lean caching: only Gradle + Maestro to stay under 10GB org-wide cache budget
      - name: Cache Gradle (caches + wrapper + project .gradle)
        id: gradle-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            android/.gradle
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'android/**/build.gradle', 'android/**/gradle.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Create debug keystore
        run: |
          mkdir -p android
          keytool -genkeypair -v \
            -keystore "android/debug.keystore" \
            -storepass android -keypass android \
            -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=Android Debug,O=Android,C=US"

      - name: Write signing props for Gradle
        run: |
          echo "android.injected.signing.store.file=$PWD/android/debug.keystore" >> android/gradle.properties
          echo "android.injected.signing.store.password=android"                 >> android/gradle.properties
          echo "android.injected.signing.key.alias=androiddebugkey"              >> android/gradle.properties
          echo "android.injected.signing.key.password=android"                   >> android/gradle.properties

      - name: Compute Android build fingerprint
        id: android_fingerprint
        shell: bash
        run: |
          set -euo pipefail

          FILES="$(git ls-files \
            'android/**' \
            'app.json' \
            'app.config.*' \
            'eas.json' \
            'package.json' \
            'package-lock.json' \
            'gradlew' \
            '**/*.gradle*' \
            'gradle.properties' \
            'babel.config.*' \
            'metro.config.*' \
            'tamagui.config.ts' \
            'tsconfig.json' \
            'index.*' \
            'src/**' \
            'assets/**' \
            '**/*.png' '**/*.svg' '**/*.ttf' '**/*.otf' \
            '.env*' \
            'patches/**' \
          )"

          # Add environment “salt” so changes in toolchain also invalidate cache
          SALT="node=$(node -v);java=$(java -version 2>&1 | head -n1)"

          if [ -z "$FILES" ]; then
            # No matching files (unlikely) – still produce a stable, non-empty key
            HASH=$( (echo "$SALT"; echo "<no-files>") | shasum -a 256 | awk '{print $1}' )
          else
            # Hash SALT + file list + per-file contents
            HASH=$( (echo "$SALT"; echo "$FILES"; echo "$FILES" | xargs -I{} shasum "{}") \
              | shasum -a 256 | awk '{print $1}' )
          fi

          echo "hash=$HASH" >> "$GITHUB_OUTPUT"
          echo "🔑 ANDROID_FINGERPRINT=$HASH"

      - name: Restore cached APK
        id: apk-cache
        uses: actions/cache/restore@v4
        with:
          path: ./*.apk
          key: android-apk-${{ steps.android_fingerprint.outputs.hash }}

      - name: Build e2erelease APK
        if: steps.apk-cache.outputs.cache-hit != 'true'
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          set -e
          ATTEMPTS="${RETRIES:-2}"
          DELAY="${RETRY_DELAY:-5}"

          for attempt in $(seq 1 "$ATTEMPTS"); do
            echo "🏗️ Build attempt $attempt/$ATTEMPTS"
            if eas build --platform android --profile e2eRelease --local --non-interactive; then
              echo "✅ Build succeeded"
              exit 0
            fi
            if [ "$attempt" -lt "$ATTEMPTS" ]; then
              echo "⚠️ Build failed; retrying in $DELAY s..."
              sleep "$DELAY"
            fi
          done

          echo "❌ Build failed after $ATTEMPTS attempts"
          exit 1

      - name: Locate APK artifact & app.json
        id: find_apk
        shell: bash
        run: |
          set -euo pipefail
          APK="$(ls -1t ./*.apk 2>/dev/null | head -n1 || true)"
          echo "APK=$APK"
          echo "apk=$APK" >> $GITHUB_OUTPUT
          [ -n "$APK" ] || (echo "No APK found in repo root."; ls -alh .; exit 1)

          PKG=$(node -p "require('./app.json').expo.android.package")
          echo "PKG=$PKG"
          echo "pkg=$PKG" >> $GITHUB_OUTPUT
          [ -n "$PKG" ] || (echo "No PKG found in repo root."; ls -alh .; exit 1)

      - name: Save APK to cache
        if: steps.apk-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: ${{ steps.find_apk.outputs.apk }}
          key: android-apk-${{ steps.android_fingerprint.outputs.hash }}

      - name: Upload Gradle reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-reports-android-selfhosted
          path: |
            android/build/reports/**
            android/app/build/reports/**
          if-no-files-found: ignore

      - name: Save Gradle cache (post-build)
        if: always() && steps.gradle-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            android/.gradle
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'android/**/build.gradle', 'android/**/gradle.properties') }}

      # Self-hosted macOS (Apple Silicon) runner must have Android SDK & emulator installed; hardware accel uses Hypervisor.framework (no KVM).
      - name: Run E2E tests
        id: e2e_android
        uses: reactivecircus/android-emulator-runner@v2
        timeout-minutes: 30 # Android emulators are slow
        with:
          api-level: ${{ env.ANDROID_API_LEVEL }}
          target: ${{ env.ANDROID_TARGET }}
          arch: arm64-v8a
          avd-name: Pixel_8
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -no-audio -no-boot-anim
          disable-animations: true
          script: .github/scripts/android_run_e2e.sh ${{ steps.find_apk.outputs.apk }} ${{ steps.find_apk.outputs.pkg }}

      - name: Upload E2E artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-artifacts-android-selfhosted
          path: |
            e2e-artifacts/**/*
            android/app/build/reports/**
          include-hidden-files: true

      - name: Clean self-hosted workspace
        if: ${{ always() }}
        shell: bash
        run: .github/scripts/clean_selfhosted_workspace.sh
