name: Quality CI

on:
  workflow_call:
    inputs:
      env_prefix:
        description: Environment prefix (PROD or DEV)
        required: true
        type: string
      runner_target:
        description: hosted or selfhosted
        required: true
        type: string

permissions:
  contents: read

concurrency:
  group: quality-${{ github.workflow }}-${{ github.run_id }}
  cancel-in-progress: true

jobs:
  quality:
    name: Quality Checks
    runs-on: ${{ fromJSON(inputs.runner_target == 'selfhosted' && '["self-hosted","macos","arm64"]' || '["ubuntu-latest"]') }}
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Prepare isolated GnuPG home for mise
        shell: bash
        run: |
          mkdir -p "${RUNNER_TEMP}/gnupg"
          chmod 700 "${RUNNER_TEMP}/gnupg"

      - name: Pin mise cache to local disk
        if: ${{ inputs.runner_target == 'selfhosted' }}
        shell: bash
        run: |
          MISE_LOCAL="$HOME/.github/local-ci-cache/mise"
          mkdir -p "$MISE_LOCAL/cache"
          echo "MISE_DATA_DIR=$MISE_LOCAL"       >> "$GITHUB_ENV"
          echo "MISE_CACHE_DIR=$MISE_LOCAL/cache" >> "$GITHUB_ENV"

      - name: Setup mise toolchain
        uses: jdx/mise-action@v3
        with:
          version: '2026.2.13'
          install: true
          cache: ${{ inputs.runner_target != 'selfhosted' }}
          log_level: ${{ runner.debug == '1' && 'debug' || 'info' }}
        env:
          GNUPGHOME: ${{ runner.temp }}/gnupg
          MISE_TRUSTED_CONFIG_PATHS: ${{ github.workspace }}

      - name: Install deps
        run: npm ci

      - name: Verify Expo/RN dependency alignment
        id: expo_deps
        shell: bash
        run: .github/scripts/verify_expo_deps.sh
        continue-on-error: true

      - name: Annotate Expo/RN dependency drift
        if: ${{ steps.expo_deps.outcome == 'failure' }}
        shell: bash
        run: |
          echo "::error::Expo/RN dependency drift detected. Run 'npx expo install --fix' and commit the lockfile changes."

      - name: Doctor
        id: expo_doctor
        run: npm run doctor
        continue-on-error: true

      - name: Annotate Expo Doctor issues
        if: ${{ steps.expo_doctor.outcome == 'failure' }}
        shell: bash
        run: |
          echo "::error::Expo Doctor reported issues. Review the Doctor step logs for details."

      - name: Check formatting
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Unit tests
        run: npm run test -- --coverage --runInBand

      - name: Install GPG
        if: ${{ !cancelled() && inputs.runner_target != 'selfhosted' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg

      - name: Upload coverage to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          slug: org/repo # <-- UPDATE THIS
          flags: ${{ inputs.runner_target }}-quality
          fail_ci_if_error: false

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./junit.xml
          slug: org/repo # <-- UPDATE THIS
          flags: ${{ inputs.runner_target }}-quality
          report_type: test_results
          fail_ci_if_error: false

      - name: Clean self-hosted workspace
        if: ${{ always() && inputs.runner_target == 'selfhosted' }}
        shell: bash
        run: .github/scripts/clean_selfhosted_workspace.sh
