name: Quality CI

on:
  workflow_call:
    inputs:
      env_prefix:
        description: Environment prefix (PROD or DEV)
        required: true
        type: string
      runner_target:
        description: hosted or selfhosted
        required: true
        type: string

permissions:
  contents: read

concurrency:
  group: quality-${{ github.workflow }}-${{ github.run_id }}
  cancel-in-progress: true

jobs:
  quality:
    name: Quality Checks
    runs-on: ${{ fromJSON(inputs.runner_target == 'selfhosted' && '["self-hosted","macos","arm64"]' || '["ubuntu-latest"]') }}
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node 24
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Doctor
        run: npm run doctor
        continue-on-error: true

      - name: Check formatting
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Unit tests
        run: npm run test -- --coverage

      - name: Install GPG
        if: ${{ !cancelled() && inputs.runner_target != 'selfhosted' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg

      - name: Upload coverage to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          slug: org/repo
          flags: ${{ inputs.runner_target }}-quality
          fail_ci_if_error: false

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./junit.xml
          slug: org/repo
          flags: ${{ inputs.runner_target }}-quality
          report_type: test_results
          fail_ci_if_error: false
